{

    "data":[
        {
            "ename":"walk",
            "cname":"走路",
            "index":"0",
            "property":[
                {
                    "ename":"distanceTraveled",
                    "cname":"总距离",
                    "value":"0.00",
                    "unit":"km"
                },
                {
                    "ename":"duration",
                    "cname":"运动时间",
                    "value":"00:00:00",
                    "unit":""
                },
                {
                    "ename":"averageSpeed",
                    "cname":"平均速度",
                    "value":"0",
                    "unit":"km/h"
                },
                {
                    "ename":"freezeDuration",
                    "cname":"休息时间",
                    "value":"00:00:00",
                    "unit":""
                },
                {
                    "ename":"nSteps",
                    "cname":"步数",
                    "value":"0",
                    "unit":""
                },
                {
                    "ename":"currentAltitude",
                    "cname":"当前海拔",
                    "value":"0",
                    "unit":"m"
                }
            ]
        },
        {
            "ename":"run",
            "cname":"跑步",
            "index":"1",
            "property":[
                {
                    "ename":"distanceTraveled",
                    "cname":"总距离",
                    "value":"0.00",
                    "unit":"km"
                },
                {
                    "ename":"duration",
                    "cname":"运动时间",
                    "value":"00:00:00",
                    "unit":""
                },
                {
                    "ename":"averageMatchSpeed",
                    "cname":"平均配速",
                    "value":"0",
                    "unit":""
                },
                {
                    "ename":"maxMatchSpeed",
                    "cname":"最快配速",
                    "value":"0",
                    "unit":""
                },
                {
                    "ename":"nSteps",
                    "cname":"步数",
                    "value":"0",
                    "unit":""
                },
                {
                    "ename":"freezeDuration",
                    "cname":"休息时间",
                    "value":"00:00:00",
                    "unit":""
                },
                {
                    "ename":"minMatchSpeed",
                    "cname":"最慢配速",
                    "value":"0",
                    "unit":""
                }
            ]
        },
        {
            "ename":"cycling",
            "cname":"自行车",
            "index":"2",
            "property":[
                {
                    "ename":"distanceTraveled",
                    "cname":"总距离",
                    "value":"0.00",
                    "unit":"km"
                },
                {
                    "ename":"duration",
                    "cname":"运动时间",
                    "value":"00:00:00",
                    "unit":""
                },
                {
                    "ename":"averageMatchSpeed",
                    "cname":"平均配速",
                    "value":"0",
                    "unit":""
                },
                {
                    "ename":"maxMatchSpeed",
                    "cname":"最快配速",
                    "value":"0",
                    "unit":""
                },
                {
                    "ename":"freezeDuration",
                    "cname":"休息时间",
                    "value":"00:00:00",
                    "unit":""
                },
                {
                    "ename":"currentAltitude",
                    "cname":"当前海拔",
                    "value":"0",
                    "unit":"m"
                }
            ]
        },
        {
            "ename":"ski",
            "cname":"单板滑雪",
            "index":"13",
            "property":[
                {
                    "ename":"distanceTraveled",
                    "cname":"总距离",
                    "value":"0.00",
                    "unit":"km"
                },
                {
                    "ename":"hopCount",
                    "cname":"趟数",
                    "value":"0",
                    "unit":"趟"
                },
                {
                    "ename":"duration",
                    "cname":"时间",
                    "value":"00:00:00",
                    "unit":""
                },
                {
                    "ename":"downHillDistance",
                    "cname":"滑行距离",
                    "value":"0",
                    "unit":"m"
                },
                {
                    "ename":"verticalDistance",
                    "cname":"滑行落差",
                    "value":"0",
                    "unit":"m"
                },
                {
                    "ename":"topSpeed",
                    "cname":"最高速度",
                    "value":"0",
                    "unit":"km/h"
                },
                {
                    "ename":"maxSlope",
                    "cname":"最大坡度",
                    "value":"0",
                    "unit":""
                },
                {
                    "ename":"currentAltitude",
                    "cname":"当前海拔",
                    "value":"0",
                    "unit":"m"
                }
            ]
        },
        {
            "ename":"skyTwo",
            "cname":"双板滑雪",
            "index":"14",
            "property":[
                {
                    "ename":"distanceTraveled",
                    "cname":"总距离",
                    "value":"0.00",
                    "unit":"km"
                },
                {
                    "ename":"hopCount",
                    "cname":"趟数",
                    "value":"0",
                    "unit":"趟"
                },
                {
                    "ename":"duration",
                    "cname":"时间",
                    "value":"00:00:00",
                    "unit":""
                },
                {
                    "ename":"downHillDistance",
                    "cname":"滑行距离",
                    "value":"0",
                    "unit":"m"
                },
                {
                    "ename":"verticalDistance",
                    "cname":"滑行落差",
                    "value":"0",
                    "unit":"m"
                },
                {
                    "ename":"topSpeed",
                    "cname":"最高速度",
                    "value":"0",
                    "unit":"km/h"
                },
                {
                    "ename":"maxSlope",
                    "cname":"最大坡度",
                    "value":"0",
                    "unit":""
                },
                {
                    "ename":"currentAltitude",
                    "cname":"当前海拔",
                    "value":"0",
                    "unit":"m"
                }
            ]
        },
        {
            "ename":"runYueYe",
            "cname":"越野跑",
            "index":"5",
            "property":[
                {
                    "ename":"distanceTraveled",
                    "cname":"总距离",
                    "value":"0.00",
                    "unit":"km"
                },
                {
                    "ename":"duration",
                    "cname":"运动时间",
                    "value":"00:00:00",
                    "unit":""
                },
                {
                    "ename":"averageMatchSpeed",
                    "cname":"平均配速",
                    "value":"0",
                    "unit":""
                },
                {
                    "ename":"maxMatchSpeed",
                    "cname":"最快配速",
                    "value":"0",
                    "unit":""
                },
                {
                    "ename":"nSteps",
                    "cname":"步数",
                    "value":"0",
                    "unit":""
                },
                {
                    "ename":"freezeDuration",
                    "cname":"休息时间",
                    "value":"00:00:00",
                    "unit":""
                },
                {
                    "ename":"currentAltitude",
                    "cname":"当前海拔",
                    "value":"0",
                    "unit":"m"
                }
            ]
        },
        {
            "ename":"driveYueYe",
            "cname":"山地车越野",
            "index":"6",
            "property":[
                {
                    "ename":"distanceTraveled",
                    "cname":"总距离",
                    "value":"0.00",
                    "unit":"km"
                },
                {
                    "ename":"duration",
                    "cname":"时间",
                    "value":"00:00:00",
                    "unit":""
                },
                {
                    "ename":"averageSpeed",
                    "cname":"平均速度",
                    "value":"0",
                    "unit":"km/h"
                },
                {
                    "ename":"freezeDuration",
                    "cname":"休息时间",
                    "value":"00:00:00",
                    "unit":""
                },
                {
                    "ename":"topSpeed",
                    "cname":"最高速度",
                    "value":"0",
                    "unit":"km/h"
                },
                {
                    "ename":"speed",
                    "cname":"当前时速",
                    "value":"0",
                    "unit":"km/h"
                },
                {
                    "ename":"currentAltitude",
                    "cname":"当前海拔",
                    "value":"0",
                    "unit":"m"
                }
            ]
        },
        {
            "ename":"skyLunHua",
            "cname":"轮滑",
            "index":"7",
            "property":[
                {
                    "ename":"distanceTraveled",
                    "cname":"总距离",
                    "value":"0.00",
                    "unit":"km"
                },
                {
                    "ename":"duration",
                    "cname":"时间",
                    "value":"00:00:00",
                    "unit":""
                },
                {
                    "ename":"averageSpeed",
                    "cname":"平均速度",
                    "value":"0",
                    "unit":"km/h"
                },
                {
                    "ename":"freezeDuration",
                    "cname":"休息时间",
                    "value":"00:00:00",
                    "unit":""
                },
                {
                    "ename":"topSpeed",
                    "cname":"最高速度",
                    "value":"0",
                    "unit":"km/h"
                },
                {
                    "ename":"speed",
                    "cname":"当前时速",
                    "value":"0",
                    "unit":"km/h"
                },
                {
                    "ename":"currentAltitude",
                    "cname":"当前海拔",
                    "value":"0",
                    "unit":"m"
                }
            ]
        },
        {
            "ename":"autobike",
            "cname":"摩托车",
            "index":"8",
            "property":[
                {
                    "ename":"distanceTraveled",
                    "cname":"总距离",
                    "value":"0.00",
                    "unit":"km"
                },
                {
                    "ename":"duration",
                    "cname":"时间",
                    "value":"00:00:00",
                    "unit":""
                },
                {
                    "ename":"averageSpeed",
                    "cname":"平均速度",
                    "value":"0",
                    "unit":"km/h"
                },
                {
                    "ename":"freezeDuration",
                    "cname":"休息时间",
                    "value":"00:00:00",
                    "unit":""
                },
                {
                    "ename":"topSpeed",
                    "cname":"最高速度",
                    "value":"0",
                    "unit":"km/h"
                },
                {
                    "ename":"speed",
                    "cname":"当前时速",
                    "value":"0",
                    "unit":"km/h"
                },
                {
                    "ename":"currentAltitude",
                    "cname":"当前海拔",
                    "value":"0",
                    "unit":"m"
                }
            ]
        },
        {
            "ename":"longboard",
            "cname":"长板",
            "index":"11",
            "property":[
                {
                    "ename":"distanceTraveled",
                    "cname":"总距离",
                    "value":"0.00",
                    "unit":"km"
                },
                {
                    "ename":"duration",
                    "cname":"时间",
                    "value":"00:00:00",
                    "unit":""
                },
                {
                    "ename":"averageSpeed",
                    "cname":"平均速度",
                    "value":"0",
                    "unit":"km/h"
                },
                {
                    "ename":"freezeDuration",
                    "cname":"休息时间",
                    "value":"00:00:00",
                    "unit":""
                },
                {
                    "ename":"topSpeed",
                    "cname":"最高速度",
                    "value":"0",
                    "unit":"km/h"
                },
                {
                    "ename":"speed",
                    "cname":"当前时速",
                    "value":"0",
                    "unit":"km/h"
                },
                {
                    "ename":"currentAltitude",
                    "cname":"当前海拔",
                    "value":"0",
                    "unit":"m"
                }
            ]
        },
        {
            "ename":"horseRiding",
            "cname":"骑马",
            "index":"12",
            "property":[
                {
                    "ename":"distanceTraveled",
                    "cname":"总距离",
                    "value":"0.00",
                    "unit":"km"
                },
                {
                    "ename":"duration",
                    "cname":"时间",
                    "value":"00:00:00",
                    "unit":""
                },
                {
                    "ename":"averageSpeed",
                    "cname":"平均速度",
                    "value":"0",
                    "unit":"km/h"
                },
                {
                    "ename":"freezeDuration",
                    "cname":"休息时间",
                    "value":"00:00:00",
                    "unit":""
                },
                {
                    "ename":"topSpeed",
                    "cname":"最高速度",
                    "value":"0",
                    "unit":"km/h"
                },
                {
                    "ename":"speed",
                    "cname":"当前时速",
                    "value":"0",
                    "unit":"km/h"
                },
                {
                    "ename":"currentAltitude",
                    "cname":"当前海拔",
                    "value":"0",
                    "unit":"m"
                }
            ]
        },
        {
            "ename":"windsurfing",
            "cname":"帆板",
            "index":"16",
            "property":[
                {
                    "ename":"distanceTraveled",
                    "cname":"总距离",
                    "value":"0.00",
                    "unit":"km"
                },
                {
                    "ename":"duration",
                    "cname":"时间",
                    "value":"00:00:00",
                    "unit":""
                },
                {
                    "ename":"averageSpeed",
                    "cname":"平均速度",
                    "value":"0",
                    "unit":"km/h"
                },
                {
                    "ename":"freezeDuration",
                    "cname":"休息时间",
                    "value":"00:00:00",
                    "unit":""
                },
                {
                    "ename":"topSpeed",
                    "cname":"最高速度",
                    "value":"0",
                    "unit":"km/h"
                },
                {
                    "ename":"speed",
                    "cname":"当前时速",
                    "value":"0",
                    "unit":"km/h"
                },
                {
                    "ename":"currentAltitude",
                    "cname":"当前海拔",
                    "value":"0",
                    "unit":"m"
                }
            ]
        },
        {
            "ename":"kitesurfing",
            "cname":"风筝冲浪",
            "index":"17",
            "property":[
                {
                    "ename":"distanceTraveled",
                    "cname":"总距离",
                    "value":"0.00",
                    "unit":"km"
                },
                {
                    "ename":"duration",
                    "cname":"时间",
                    "value":"00:00:00",
                    "unit":""
                },
                {
                    "ename":"averageSpeed",
                    "cname":"平均速度",
                    "value":"0",
                    "unit":"km/h"
                },
                {
                    "ename":"freezeDuration",
                    "cname":"休息时间",
                    "value":"00:00:00",
                    "unit":""
                },
                {
                    "ename":"topSpeed",
                    "cname":"最高速度",
                    "value":"0",
                    "unit":"km/h"
                },
                {
                    "ename":"speed",
                    "cname":"当前时速",
                    "value":"0",
                    "unit":"km/h"
                },
                {
                    "ename":"currentAltitude",
                    "cname":"当前海拔",
                    "value":"0",
                    "unit":"m"
                }
            ]
        },
        {
            "ename":"driving",
            "cname":"开车",
            "index":"3",
            "property":[
                {
                    "ename":"distanceTraveled",
                    "cname":"总距离",
                    "value":"0.00",
                    "unit":"km"
                },
                {
                    "ename":"duration",
                    "cname":"时间",
                    "value":"00:00:00",
                    "unit":""
                },
                {
                    "ename":"averageSpeed",
                    "cname":"平均速度",
                    "value":"0",
                    "unit":"km/h"
                },
                {
                    "ename":"freezeDuration",
                    "cname":"休息时间",
                    "value":"00:00:00",
                    "unit":""
                },
                {
                    "ename":"topSpeed",
                    "cname":"最高速度",
                    "value":"0",
                    "unit":"km/h"
                },
                {
                    "ename":"speed",
                    "cname":"当前时速",
                    "value":"0",
                    "unit":"km/h"
                },
                {
                    "ename":"currentAltitude",
                    "cname":"当前海拔",
                    "value":"0",
                    "unit":"m"
                }
            ]
        },
        {
            "ename":"othersport",
            "cname":"其他运动",
            "index":"-1",
            "property":[
                {
                    "ename":"distanceTraveled",
                    "cname":"总距离",
                    "value":"0.00",
                    "unit":"km"
                },
                {
                    "ename":"duration",
                    "cname":"时间",
                    "value":"00:00:00",
                    "unit":""
                },
                {
                    "ename":"averageSpeed",
                    "cname":"平均速度",
                    "value":"0",
                    "unit":"km/h"
                },
                {
                    "ename":"freezeDuration",
                    "cname":"休息时间",
                    "value":"00:00:00",
                    "unit":""
                },
                {
                    "ename":"topSpeed",
                    "cname":"最高速度",
                    "value":"0",
                    "unit":"km/h"
                },
                {
                    "ename":"speed",
                    "cname":"当前时速",
                    "value":"0",
                    "unit":"km/h"
                },
                {
                    "ename":"currentAltitude",
                    "cname":"当前海拔",
                    "value":"0",
                    "unit":"m"
                }
            ]
        }
    ],
    "status":200

}