{

    "data":[
        {
            "ename":"run",
            "cname":"跑步",
            "property":[
                {
                    "ename":"distanceTraveled",
                    "cname":"总距离",
                    "value":"0.0",
                    "unit":"km"
                },
                {
                    "ename":"duration",
                    "cname":"运动时间",
                    "value":"00:00:00",
                    "unit":""
                },
                {
                    "ename":"matchSpeed",
                    "cname":"配速",
                    "value":"0",
                    "unit":"km/h"
                },
                {
                    "ename":"freezeDuration",
                    "cname":"休息时间",
                    "value":"00:00:00",
                    "unit":""
                },
                {
                    "ename":"nSteps",
                    "cname":"步数",
                    "value":"0",
                    "unit":""
                },
                {
                    "ename":"maxMatchSpeed",
                    "cname":"最快配速",
                    "value":"0",
                    "unit":"km/h"
                },
                {
                    "ename":"averageMatchSpeed",
                    "cname":"平均配速",
                    "value":"0",
                    "unit":"km/h"
                },
                {
                    "ename":"currentAltitude",
                    "cname":"当前海拔",
                    "value":"0",
                    "unit":"m"
                }
            ]
        },
        {
            "ename":"riding",
            "cname":"骑行",
            "property":[
                {
                    "ename":"distanceTraveled",
                    "cname":"总距离",
                    "value":"0.0",
                    "unit":"km"
                },
                {
                    "ename":"duration",
                    "cname":"运动时间",
                    "value":"00:00:00",
                    "unit":""
                },
                {
                    "ename":"matchSpeed",
                    "cname":"配速",
                    "value":"0",
                    "unit":"km/h"
                },
                {
                    "ename":"freezeDuration",
                    "cname":"休息时间",
                    "value":"00:00:00",
                    "unit":""
                },
                {
                    "ename":"maxMatchSpeed",
                    "cname":"最快配速",
                    "value":"0",
                    "unit":"km/h"
                },
                {
                    "ename":"averageMatchSpeed",
                    "cname":"平均配速",
                    "value":"0",
                    "unit":"km/h"
                },
                {
                    "ename":"currentAltitude",
                    "cname":"当前海拔",
                    "value":"0",
                    "unit":"m"
                }
            ]
        },
        {
            "ename":"walk",
            "cname":"走路",
            "property":[
                {
                    "ename":"distanceTraveled",
                    "cname":"总距离",
                    "value":"0.0",
                    "unit":"km"
                },
                {
                    "ename":"duration",
                    "cname":"运动时间",
                    "value":"00:00:00",
                    "unit":""
                },
                {
                    "ename":"averageSpeed",
                    "cname":"平均速度",
                    "value":"0",
                    "unit":"km/h"
                },
                {
                    "ename":"freezeDuration",
                    "cname":"休息时间",
                    "value":"00:00:00",
                    "unit":""
                },
                {
                    "ename":"nSteps",
                    "cname":"步数",
                    "value":"0",
                    "unit":""
                },
                {
                    "ename":"currentAltitude",
                    "cname":"当前海拔",
                    "value":"0",
                    "unit":"m"
                }
            ]
        },
        {
            "ename":"ski",
            "cname":"滑雪",
            "property":[
                {
                    "ename":"distanceTraveled",
                    "cname":"总距离",
                    "value":"0.0",
                    "unit":"km"
                },
                {
                    "ename":"hopCount",
                    "cname":"趟数",
                    "value":"0",
                    "unit":"圈"
                },
                {
                    "ename":"duration",
                    "cname":"时间",
                    "value":"00:00:00",
                    "unit":""
                },
                {
                    "ename":"downHillDistance",
                    "cname":"滑行距离",
                    "value":"0",
                    "unit":"m"
                },
                {
                    "ename":"verticalDistance",
                    "cname":"滑行落差",
                    "value":"0",
                    "unit":"m"
                },
                {
                    "ename":"maxMatchSpeed",
                    "cname":"最大速度",
                    "value":"0",
                    "unit":"m"
                },
                {
                    "ename":"maxSlope",
                    "cname":"最大坡度",
                    "value":"0",
                    "unit":"km/h"
                },
                {
                    "ename":"currentAltitude",
                    "cname":"当前海拔",
                    "value":"0",
                    "unit":"m"
                }
            ]
        }
    ],
    "status":200

}