/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_longcheng_lifecareplan_utils_bspatch_BsPatchUtil */

#ifndef _Included_com_longcheng_lifecareplan_utils_bspatch_BsPatchUtil
#define _Included_com_longcheng_lifecareplan_utils_bspatch_BsPatchUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_longcheng_lifecareplan_utils_bspatch_BsPatchUtil
 * Method:    patch
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_longcheng_lifecareplan_utils_bspatch_BsPatchUtil_patch
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
